# Generated by Django 4.0 on 2025-06-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penjurusan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjurusan',
            name='jurusan_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurusan_utama', to='penjurusan.jurusan'),
        ),
        migrations.AddField(
            model_name='penjurusan',
            name='jurusan_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurusan_alternatif_1', to='penjurusan.jurusan'),
        ),
        migrations.AddField(
            model_name='penjurusan',
            name='jurusan_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurusan_alternatif_2', to='penjurusan.jurusan'),
        ),
    ]
