# Generated by Django 4.0 on 2025-06-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penjurusan', '0002_penjurusan_jurusan_1_penjurusan_jurusan_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjurusan',
            name='jurusan',
        ),
    ]
